// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package server

type User struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	LuckyNumber *int   `json:"luckyNumber"`
}
