package example

// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

import (
	"context"
	"time"

	"github.com/Khan/genqlient/graphql"
)

type getUserResponse struct {
	User getUserUser `json:"user"`
}

type getUserUser struct {
	TheirName string    `json:"theirName"`
	CreatedAt time.Time `json:"createdAt"`
}

type getViewerResponse struct {
	Viewer getViewerViewerUser `json:"viewer"`
}

type getViewerViewerUser struct {
	MyName    string
	CreatedAt time.Time `json:"createdAt"`
}

func getViewer(
	ctx context.Context,
	client graphql.Client,
) (*getViewerResponse, error) {
	var retval getViewerResponse
	err := client.MakeRequest(
		ctx,
		"getViewer",
		`
query getViewer {
	viewer {
		MyName: name
		createdAt
	}
}
`,
		&retval,
		nil,
	)
	return &retval, err
}

// getUser gets the given user's name from their username.
func getUser(
	ctx context.Context,
	client graphql.Client,
	login string,
) (*getUserResponse, error) {
	variables := map[string]interface{}{
		"Login": login,
	}

	var retval getUserResponse
	err := client.MakeRequest(
		ctx,
		"getUser",
		`
query getUser ($Login: String!) {
	user(login: $Login) {
		theirName: name
		createdAt
	}
}
`,
		&retval,
		variables,
	)
	return &retval, err
}
