package test

// Code generated by github.com/Khan/genql, DO NOT EDIT.

import (
	"context"

	"github.com/Khan/genql/graphql"
)

type ListInputQueryResponse struct {
	User *User `json:"user"`
}

type User struct {
	Id string `json:"id"`
}

func ListInputQuery(client *graphql.Client, names []*string) (*ListInputQueryResponse, error) {
	variables := map[string]interface{}{
		"names": names,
	}

	var retval ListInputQueryResponse
	err := client.MakeRequest(context.Background(), `
query ListInputQuery ($names: [String]) {
	user(query: {names:$names}) {
		id
	}
}
`, &retval, variables)
	return &retval, err
}
