package test

// Code generated by github.com/Khan/genql, DO NOT EDIT.

import (
	"context"

	"github.com/Khan/genql/graphql"
)

type QueryWithEnumsResponse struct {
	User *User `json:"user"`
}

type Role string

const (
	StudentRole Role = "STUDENT"
	TeacherRole Role = "TEACHER"
)

type User struct {
	Roles []Role `json:"roles"`
}

func QueryWithEnums(client *graphql.Client) (*QueryWithEnumsResponse, error) {
	var retval QueryWithEnumsResponse
	err := client.MakeRequest(context.Background(), `
query QueryWithEnums {
	user {
		roles
	}
}
`, &retval, nil)
	return &retval, err
}
