package test

// Code generated by github.com/Khan/genql, DO NOT EDIT.

import (
	"context"

	"github.com/Khan/genql/graphql"
)

type SimpleQueryResponse struct {
	User *User `json:"user"`
}

type User struct {
	Id string `json:"id"`
}

func SimpleQuery(client *graphql.Client) (*SimpleQueryResponse, error) {
	var retval SimpleQueryResponse
	err := client.MakeRequest(context.Background(), `
query SimpleQuery {
	user {
		id
	}
}
`, &retval, nil)
	return &retval, err
}
