package test

// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

import (
	"github.com/Khan/genqlient/graphql"
)

type QueryWithEnumsOtherUser struct {
	Roles []Role `json:"roles"`
}

type QueryWithEnumsResponse struct {
	User      QueryWithEnumsUser      `json:"user"`
	OtherUser QueryWithEnumsOtherUser `json:"otherUser"`
}

type QueryWithEnumsUser struct {
	Roles []Role `json:"roles"`
}

type Role string

const (
	RoleStudent Role = "STUDENT"
	RoleTeacher Role = "TEACHER"
)

func QueryWithEnums(
	client graphql.Client,
) (*QueryWithEnumsResponse, error) {
	var retval QueryWithEnumsResponse
	err := client.MakeRequest(
		nil,
		"QueryWithEnums",
		`
query QueryWithEnums {
	user {
		roles
	}
	otherUser: user {
		roles
	}
}
`,
		&retval,
		nil,
	)
	return &retval, err
}
