package test

// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

import (
	"github.com/Khan/genqlient/graphql"
)

type SimpleMutationCreateUser struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type SimpleMutationResponse struct {
	CreateUser SimpleMutationCreateUser `json:"createUser"`
}

// SimpleMutation creates a user.
//
// It has a long doc-comment, to test that we handle that correctly.
// What a long comment indeed.
func SimpleMutation(
	client graphql.Client,
	name string,
) (*SimpleMutationResponse, error) {
	variables := map[string]interface{}{
		"name": name,
	}

	var retval SimpleMutationResponse
	err := client.MakeRequest(
		nil,
		"SimpleMutation",
		`
mutation SimpleMutation ($name: String!) {
	createUser(name: $name) {
		id
		name
	}
}
`,
		&retval,
		variables,
	)
	return &retval, err
}
