package test

// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

import (
	"github.com/Khan/genqlient/graphql"
	"github.com/me/mypkg"
)

type TypeNameQueryResponse struct {
	User TypeNameQueryUser `json:"user"`
}

type TypeNameQueryUser struct {
	Typename string   `json:"__typename"`
	Id       mypkg.ID `json:"id"`
}

func TypeNameQuery(
	client graphql.Client,
) (*TypeNameQueryResponse, error) {
	var retval TypeNameQueryResponse
	err := client.MakeRequest(
		nil,
		"TypeNameQuery",
		`
query TypeNameQuery {
	user {
		__typename
		id
	}
}
`,
		&retval,
		nil,
	)
	return &retval, err
}
