package test

// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

import (
	"github.com/Khan/genqlient/graphql"
)

type Role string

const (
	RoleStudent Role = "STUDENT"
	RoleTeacher Role = "TEACHER"
)

type UsesEnumTwiceQueryMeUser struct {
	Roles []Role `json:"roles"`
}

type UsesEnumTwiceQueryOtherUser struct {
	Roles []Role `json:"roles"`
}

type UsesEnumTwiceQueryResponse struct {
	Me        UsesEnumTwiceQueryMeUser
	OtherUser UsesEnumTwiceQueryOtherUser
}

func UsesEnumTwiceQuery(
	client graphql.Client,
) (*UsesEnumTwiceQueryResponse, error) {
	var retval UsesEnumTwiceQueryResponse
	err := client.MakeRequest(
		nil,
		"UsesEnumTwiceQuery",
		`
query UsesEnumTwiceQuery {
	Me: user {
		roles
	}
	OtherUser: user {
		roles
	}
}
`,
		&retval,
		nil,
	)
	return &retval, err
}
