// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package queries

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/Khan/genqlient/graphql"
)

// OmitImplsUnionRandomLeafArticle includes the requested fields of the GraphQL type Article.
type OmitImplsUnionRandomLeafArticle struct {
	Typename string `json:"__typename"`
	// ID is documented in the Content interface.
	Id   string `json:"id"`
	Text string `json:"text"`
}

// GetTypename returns OmitImplsUnionRandomLeafArticle.Typename, and is useful for accessing the field via an interface.
func (v *OmitImplsUnionRandomLeafArticle) GetTypename() string { return v.Typename }

// GetId returns OmitImplsUnionRandomLeafArticle.Id, and is useful for accessing the field via an interface.
func (v *OmitImplsUnionRandomLeafArticle) GetId() string { return v.Id }

// GetText returns OmitImplsUnionRandomLeafArticle.Text, and is useful for accessing the field via an interface.
func (v *OmitImplsUnionRandomLeafArticle) GetText() string { return v.Text }

// OmitImplsUnionRandomLeafLeafContent includes the requested fields of the GraphQL interface LeafContent.
//
// OmitImplsUnionRandomLeafLeafContent is implemented by the following types:
// OmitImplsUnionRandomLeafArticle
// OmitImplsUnionRandomLeafLeafContentGenqlientOther
// The GraphQL type's documentation follows.
//
// LeafContent represents content items that can't have child-nodes.
type OmitImplsUnionRandomLeafLeafContent interface {
	implementsGraphQLInterfaceOmitImplsUnionRandomLeafLeafContent()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
}

func (v *OmitImplsUnionRandomLeafArticle) implementsGraphQLInterfaceOmitImplsUnionRandomLeafLeafContent() {
}
func (v *OmitImplsUnionRandomLeafLeafContentGenqlientOther) implementsGraphQLInterfaceOmitImplsUnionRandomLeafLeafContent() {
}

func __unmarshalOmitImplsUnionRandomLeafLeafContent(b []byte, v *OmitImplsUnionRandomLeafLeafContent) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "Article":
		*v = new(OmitImplsUnionRandomLeafArticle)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing LeafContent.__typename")
	default:
		*v = new(OmitImplsUnionRandomLeafLeafContentGenqlientOther)
		return json.Unmarshal(b, *v)
	}
}

func __marshalOmitImplsUnionRandomLeafLeafContent(v *OmitImplsUnionRandomLeafLeafContent) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *OmitImplsUnionRandomLeafArticle:
		typename = "Article"

		result := struct {
			TypeName string `json:"__typename"`
			*OmitImplsUnionRandomLeafArticle
		}{typename, v}
		return json.Marshal(result)
	case *OmitImplsUnionRandomLeafLeafContentGenqlientOther:
		return json.Marshal(v)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for OmitImplsUnionRandomLeafLeafContent: "%T"`, v)
	}
}

// OmitImplsUnionRandomLeafLeafContentGenqlientOther is the catch-all for OmitImplsUnionRandomLeafLeafContent implementations that aren't explicitly fragmented; the concrete type-name is in __typename.
type OmitImplsUnionRandomLeafLeafContentGenqlientOther struct {
	Typename string `json:"__typename"`
}

// GetTypename returns OmitImplsUnionRandomLeafLeafContentGenqlientOther.Typename, and is useful for accessing the field via an interface.
func (v *OmitImplsUnionRandomLeafLeafContentGenqlientOther) GetTypename() string { return v.Typename }

// OmitImplsUnionResponse is returned by OmitImplsUnion on success.
type OmitImplsUnionResponse struct {
	RandomLeaf OmitImplsUnionRandomLeafLeafContent `json:"-"`
}

// GetRandomLeaf returns OmitImplsUnionResponse.RandomLeaf, and is useful for accessing the field via an interface.
func (v *OmitImplsUnionResponse) GetRandomLeaf() OmitImplsUnionRandomLeafLeafContent {
	return v.RandomLeaf
}

func (v *OmitImplsUnionResponse) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*OmitImplsUnionResponse
		RandomLeaf json.RawMessage `json:"randomLeaf"`
		graphql.NoUnmarshalJSON
	}
	firstPass.OmitImplsUnionResponse = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.RandomLeaf
		src := firstPass.RandomLeaf
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalOmitImplsUnionRandomLeafLeafContent(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal OmitImplsUnionResponse.RandomLeaf: %w", err)
			}
		}
	}
	return nil
}

type __premarshalOmitImplsUnionResponse struct {
	RandomLeaf json.RawMessage `json:"randomLeaf"`
}

func (v *OmitImplsUnionResponse) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *OmitImplsUnionResponse) __premarshalJSON() (*__premarshalOmitImplsUnionResponse, error) {
	var retval __premarshalOmitImplsUnionResponse

	{

		dst := &retval.RandomLeaf
		src := v.RandomLeaf
		var err error
		*dst, err = __marshalOmitImplsUnionRandomLeafLeafContent(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal OmitImplsUnionResponse.RandomLeaf: %w", err)
		}
	}
	return &retval, nil
}

// The query executed by OmitImplsUnion.
const OmitImplsUnion_Operation = `
query OmitImplsUnion {
	randomLeaf {
		__typename
		... on Article {
			id
			text
		}
	}
}
`

func OmitImplsUnion(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *OmitImplsUnionResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "OmitImplsUnion",
		Query:  OmitImplsUnion_Operation,
	}

	data_ = &OmitImplsUnionResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

