// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package queries

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/Khan/genqlient/graphql"
)

// OmitImplsAllImplsReferencedRandomLeafArticle includes the requested fields of the GraphQL type Article.
type OmitImplsAllImplsReferencedRandomLeafArticle struct {
	Typename string `json:"__typename"`
	// ID is documented in the Content interface.
	Id   string `json:"id"`
	Text string `json:"text"`
}

// GetTypename returns OmitImplsAllImplsReferencedRandomLeafArticle.Typename, and is useful for accessing the field via an interface.
func (v *OmitImplsAllImplsReferencedRandomLeafArticle) GetTypename() string { return v.Typename }

// GetId returns OmitImplsAllImplsReferencedRandomLeafArticle.Id, and is useful for accessing the field via an interface.
func (v *OmitImplsAllImplsReferencedRandomLeafArticle) GetId() string { return v.Id }

// GetText returns OmitImplsAllImplsReferencedRandomLeafArticle.Text, and is useful for accessing the field via an interface.
func (v *OmitImplsAllImplsReferencedRandomLeafArticle) GetText() string { return v.Text }

// OmitImplsAllImplsReferencedRandomLeafLeafContent includes the requested fields of the GraphQL interface LeafContent.
//
// OmitImplsAllImplsReferencedRandomLeafLeafContent is implemented by the following types:
// OmitImplsAllImplsReferencedRandomLeafArticle
// OmitImplsAllImplsReferencedRandomLeafVideo
// OmitImplsAllImplsReferencedRandomLeafLeafContentGenqlientOther
// The GraphQL type's documentation follows.
//
// LeafContent represents content items that can't have child-nodes.
type OmitImplsAllImplsReferencedRandomLeafLeafContent interface {
	implementsGraphQLInterfaceOmitImplsAllImplsReferencedRandomLeafLeafContent()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
}

func (v *OmitImplsAllImplsReferencedRandomLeafArticle) implementsGraphQLInterfaceOmitImplsAllImplsReferencedRandomLeafLeafContent() {
}
func (v *OmitImplsAllImplsReferencedRandomLeafVideo) implementsGraphQLInterfaceOmitImplsAllImplsReferencedRandomLeafLeafContent() {
}
func (v *OmitImplsAllImplsReferencedRandomLeafLeafContentGenqlientOther) implementsGraphQLInterfaceOmitImplsAllImplsReferencedRandomLeafLeafContent() {
}

func __unmarshalOmitImplsAllImplsReferencedRandomLeafLeafContent(b []byte, v *OmitImplsAllImplsReferencedRandomLeafLeafContent) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "Article":
		*v = new(OmitImplsAllImplsReferencedRandomLeafArticle)
		return json.Unmarshal(b, *v)
	case "Video":
		*v = new(OmitImplsAllImplsReferencedRandomLeafVideo)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing LeafContent.__typename")
	default:
		*v = new(OmitImplsAllImplsReferencedRandomLeafLeafContentGenqlientOther)
		return json.Unmarshal(b, *v)
	}
}

func __marshalOmitImplsAllImplsReferencedRandomLeafLeafContent(v *OmitImplsAllImplsReferencedRandomLeafLeafContent) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *OmitImplsAllImplsReferencedRandomLeafArticle:
		typename = "Article"

		result := struct {
			TypeName string `json:"__typename"`
			*OmitImplsAllImplsReferencedRandomLeafArticle
		}{typename, v}
		return json.Marshal(result)
	case *OmitImplsAllImplsReferencedRandomLeafVideo:
		typename = "Video"

		result := struct {
			TypeName string `json:"__typename"`
			*OmitImplsAllImplsReferencedRandomLeafVideo
		}{typename, v}
		return json.Marshal(result)
	case *OmitImplsAllImplsReferencedRandomLeafLeafContentGenqlientOther:
		return json.Marshal(v)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for OmitImplsAllImplsReferencedRandomLeafLeafContent: "%T"`, v)
	}
}

// OmitImplsAllImplsReferencedRandomLeafLeafContentGenqlientOther is the catch-all for OmitImplsAllImplsReferencedRandomLeafLeafContent implementations that aren't explicitly fragmented; the concrete type-name is in __typename.
type OmitImplsAllImplsReferencedRandomLeafLeafContentGenqlientOther struct {
	Typename string `json:"__typename"`
}

// GetTypename returns OmitImplsAllImplsReferencedRandomLeafLeafContentGenqlientOther.Typename, and is useful for accessing the field via an interface.
func (v *OmitImplsAllImplsReferencedRandomLeafLeafContentGenqlientOther) GetTypename() string {
	return v.Typename
}

// OmitImplsAllImplsReferencedRandomLeafVideo includes the requested fields of the GraphQL type Video.
type OmitImplsAllImplsReferencedRandomLeafVideo struct {
	Typename string `json:"__typename"`
	// ID is documented in the Content interface.
	Id       string `json:"id"`
	Duration int    `json:"duration"`
}

// GetTypename returns OmitImplsAllImplsReferencedRandomLeafVideo.Typename, and is useful for accessing the field via an interface.
func (v *OmitImplsAllImplsReferencedRandomLeafVideo) GetTypename() string { return v.Typename }

// GetId returns OmitImplsAllImplsReferencedRandomLeafVideo.Id, and is useful for accessing the field via an interface.
func (v *OmitImplsAllImplsReferencedRandomLeafVideo) GetId() string { return v.Id }

// GetDuration returns OmitImplsAllImplsReferencedRandomLeafVideo.Duration, and is useful for accessing the field via an interface.
func (v *OmitImplsAllImplsReferencedRandomLeafVideo) GetDuration() int { return v.Duration }

// OmitImplsAllImplsReferencedResponse is returned by OmitImplsAllImplsReferenced on success.
type OmitImplsAllImplsReferencedResponse struct {
	RandomLeaf OmitImplsAllImplsReferencedRandomLeafLeafContent `json:"-"`
}

// GetRandomLeaf returns OmitImplsAllImplsReferencedResponse.RandomLeaf, and is useful for accessing the field via an interface.
func (v *OmitImplsAllImplsReferencedResponse) GetRandomLeaf() OmitImplsAllImplsReferencedRandomLeafLeafContent {
	return v.RandomLeaf
}

func (v *OmitImplsAllImplsReferencedResponse) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*OmitImplsAllImplsReferencedResponse
		RandomLeaf json.RawMessage `json:"randomLeaf"`
		graphql.NoUnmarshalJSON
	}
	firstPass.OmitImplsAllImplsReferencedResponse = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.RandomLeaf
		src := firstPass.RandomLeaf
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalOmitImplsAllImplsReferencedRandomLeafLeafContent(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal OmitImplsAllImplsReferencedResponse.RandomLeaf: %w", err)
			}
		}
	}
	return nil
}

type __premarshalOmitImplsAllImplsReferencedResponse struct {
	RandomLeaf json.RawMessage `json:"randomLeaf"`
}

func (v *OmitImplsAllImplsReferencedResponse) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *OmitImplsAllImplsReferencedResponse) __premarshalJSON() (*__premarshalOmitImplsAllImplsReferencedResponse, error) {
	var retval __premarshalOmitImplsAllImplsReferencedResponse

	{

		dst := &retval.RandomLeaf
		src := v.RandomLeaf
		var err error
		*dst, err = __marshalOmitImplsAllImplsReferencedRandomLeafLeafContent(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal OmitImplsAllImplsReferencedResponse.RandomLeaf: %w", err)
		}
	}
	return &retval, nil
}

// The query executed by OmitImplsAllImplsReferenced.
const OmitImplsAllImplsReferenced_Operation = `
query OmitImplsAllImplsReferenced {
	randomLeaf {
		__typename
		... on Article {
			id
			text
		}
		... on Video {
			id
			duration
		}
	}
}
`

func OmitImplsAllImplsReferenced(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *OmitImplsAllImplsReferencedResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "OmitImplsAllImplsReferenced",
		Query:  OmitImplsAllImplsReferenced_Operation,
	}

	data_ = &OmitImplsAllImplsReferencedResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

