// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package test

import (
	"encoding/json"
	"fmt"

	"github.com/Khan/genqlient/graphql"
	"github.com/Khan/genqlient/internal/testutil"
)

// ContentBasics includes the GraphQL fields of Content requested by the fragment ContentBasics.
// The GraphQL type's documentation follows.
//
// Content is implemented by various types like Article, Video, and Topic.
//
// ContentBasics is implemented by the following types:
// ContentBasicsArticle
// ContentBasicsTopic
// ContentBasicsVideo
type ContentBasics interface {
	implementsGraphQLInterfaceContentBasics()
	// GetId returns the interface-field "id" from its implementation.
	// The GraphQL interface field's documentation follows.
	//
	// ID is the identifier of the content.
	GetId() testutil.ID
	// GetName returns the interface-field "name" from its implementation.
	GetName() string
}

func (v *ContentBasicsArticle) implementsGraphQLInterfaceContentBasics() {}
func (v *ContentBasicsTopic) implementsGraphQLInterfaceContentBasics()   {}
func (v *ContentBasicsVideo) implementsGraphQLInterfaceContentBasics()   {}

func __unmarshalContentBasics(b []byte, v *ContentBasics) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "Article":
		*v = new(ContentBasicsArticle)
		return json.Unmarshal(b, *v)
	case "Topic":
		*v = new(ContentBasicsTopic)
		return json.Unmarshal(b, *v)
	case "Video":
		*v = new(ContentBasicsVideo)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing Content.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for ContentBasics: "%v"`, tn.TypeName)
	}
}

func __marshalContentBasics(v *ContentBasics) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *ContentBasicsArticle:
		typename = "Article"

		result := struct {
			TypeName string `json:"__typename"`
			*ContentBasicsArticle
		}{typename, v}
		return json.Marshal(result)
	case *ContentBasicsTopic:
		typename = "Topic"

		result := struct {
			TypeName string `json:"__typename"`
			*ContentBasicsTopic
		}{typename, v}
		return json.Marshal(result)
	case *ContentBasicsVideo:
		typename = "Video"

		result := struct {
			TypeName string `json:"__typename"`
			*ContentBasicsVideo
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for ContentBasics: "%T"`, v)
	}
}

// ContentBasics includes the GraphQL fields of Article requested by the fragment ContentBasics.
// The GraphQL type's documentation follows.
//
// Content is implemented by various types like Article, Video, and Topic.
type ContentBasicsArticle struct {
	// ID is the identifier of the content.
	Id   testutil.ID `json:"id"`
	Name string      `json:"name"`
}

// GetId returns ContentBasicsArticle.Id, and is useful for accessing the field via an interface.
func (v *ContentBasicsArticle) GetId() testutil.ID { return v.Id }

// GetName returns ContentBasicsArticle.Name, and is useful for accessing the field via an interface.
func (v *ContentBasicsArticle) GetName() string { return v.Name }

// ContentBasics includes the GraphQL fields of Topic requested by the fragment ContentBasics.
// The GraphQL type's documentation follows.
//
// Content is implemented by various types like Article, Video, and Topic.
type ContentBasicsTopic struct {
	// ID is the identifier of the content.
	Id   testutil.ID `json:"id"`
	Name string      `json:"name"`
}

// GetId returns ContentBasicsTopic.Id, and is useful for accessing the field via an interface.
func (v *ContentBasicsTopic) GetId() testutil.ID { return v.Id }

// GetName returns ContentBasicsTopic.Name, and is useful for accessing the field via an interface.
func (v *ContentBasicsTopic) GetName() string { return v.Name }

// ContentBasics includes the GraphQL fields of Video requested by the fragment ContentBasics.
// The GraphQL type's documentation follows.
//
// Content is implemented by various types like Article, Video, and Topic.
type ContentBasicsVideo struct {
	// ID is the identifier of the content.
	Id   testutil.ID `json:"id"`
	Name string      `json:"name"`
}

// GetId returns ContentBasicsVideo.Id, and is useful for accessing the field via an interface.
func (v *ContentBasicsVideo) GetId() testutil.ID { return v.Id }

// GetName returns ContentBasicsVideo.Name, and is useful for accessing the field via an interface.
func (v *ContentBasicsVideo) GetName() string { return v.Name }

// OmitImplsAbstractFragmentInConcreteRandomItemArticle includes the requested fields of the GraphQL type Article.
type OmitImplsAbstractFragmentInConcreteRandomItemArticle struct {
	Typename string `json:"__typename"`
	// ID is the identifier of the content.
	Id                   testutil.ID `json:"id"`
	Text                 string      `json:"text"`
	ContentBasicsArticle `json:"-"`
}

// GetTypename returns OmitImplsAbstractFragmentInConcreteRandomItemArticle.Typename, and is useful for accessing the field via an interface.
func (v *OmitImplsAbstractFragmentInConcreteRandomItemArticle) GetTypename() string {
	return v.Typename
}

// GetId returns OmitImplsAbstractFragmentInConcreteRandomItemArticle.Id, and is useful for accessing the field via an interface.
func (v *OmitImplsAbstractFragmentInConcreteRandomItemArticle) GetId() testutil.ID { return v.Id }

// GetText returns OmitImplsAbstractFragmentInConcreteRandomItemArticle.Text, and is useful for accessing the field via an interface.
func (v *OmitImplsAbstractFragmentInConcreteRandomItemArticle) GetText() string { return v.Text }

// GetName returns OmitImplsAbstractFragmentInConcreteRandomItemArticle.Name, and is useful for accessing the field via an interface.
func (v *OmitImplsAbstractFragmentInConcreteRandomItemArticle) GetName() string {
	return v.ContentBasicsArticle.Name
}

func (v *OmitImplsAbstractFragmentInConcreteRandomItemArticle) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*OmitImplsAbstractFragmentInConcreteRandomItemArticle
		graphql.NoUnmarshalJSON
	}
	firstPass.OmitImplsAbstractFragmentInConcreteRandomItemArticle = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.ContentBasicsArticle)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalOmitImplsAbstractFragmentInConcreteRandomItemArticle struct {
	Typename string `json:"__typename"`

	Id testutil.ID `json:"id"`

	Text string `json:"text"`

	Name string `json:"name"`
}

func (v *OmitImplsAbstractFragmentInConcreteRandomItemArticle) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *OmitImplsAbstractFragmentInConcreteRandomItemArticle) __premarshalJSON() (*__premarshalOmitImplsAbstractFragmentInConcreteRandomItemArticle, error) {
	var retval __premarshalOmitImplsAbstractFragmentInConcreteRandomItemArticle

	retval.Typename = v.Typename
	retval.Id = v.Id
	retval.Text = v.Text
	retval.Name = v.ContentBasicsArticle.Name
	return &retval, nil
}

// OmitImplsAbstractFragmentInConcreteRandomItemContent includes the requested fields of the GraphQL interface Content.
//
// OmitImplsAbstractFragmentInConcreteRandomItemContent is implemented by the following types:
// OmitImplsAbstractFragmentInConcreteRandomItemArticle
// OmitImplsAbstractFragmentInConcreteRandomItemTopic
// OmitImplsAbstractFragmentInConcreteRandomItemVideo
// The GraphQL type's documentation follows.
//
// Content is implemented by various types like Article, Video, and Topic.
type OmitImplsAbstractFragmentInConcreteRandomItemContent interface {
	implementsGraphQLInterfaceOmitImplsAbstractFragmentInConcreteRandomItemContent()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
	// GetId returns the interface-field "id" from its implementation.
	// The GraphQL interface field's documentation follows.
	//
	// ID is the identifier of the content.
	GetId() testutil.ID
}

func (v *OmitImplsAbstractFragmentInConcreteRandomItemArticle) implementsGraphQLInterfaceOmitImplsAbstractFragmentInConcreteRandomItemContent() {
}
func (v *OmitImplsAbstractFragmentInConcreteRandomItemTopic) implementsGraphQLInterfaceOmitImplsAbstractFragmentInConcreteRandomItemContent() {
}
func (v *OmitImplsAbstractFragmentInConcreteRandomItemVideo) implementsGraphQLInterfaceOmitImplsAbstractFragmentInConcreteRandomItemContent() {
}

func __unmarshalOmitImplsAbstractFragmentInConcreteRandomItemContent(b []byte, v *OmitImplsAbstractFragmentInConcreteRandomItemContent) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "Article":
		*v = new(OmitImplsAbstractFragmentInConcreteRandomItemArticle)
		return json.Unmarshal(b, *v)
	case "Topic":
		*v = new(OmitImplsAbstractFragmentInConcreteRandomItemTopic)
		return json.Unmarshal(b, *v)
	case "Video":
		*v = new(OmitImplsAbstractFragmentInConcreteRandomItemVideo)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing Content.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for OmitImplsAbstractFragmentInConcreteRandomItemContent: "%v"`, tn.TypeName)
	}
}

func __marshalOmitImplsAbstractFragmentInConcreteRandomItemContent(v *OmitImplsAbstractFragmentInConcreteRandomItemContent) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *OmitImplsAbstractFragmentInConcreteRandomItemArticle:
		typename = "Article"

		premarshaled, err := v.__premarshalJSON()
		if err != nil {
			return nil, err
		}
		result := struct {
			TypeName string `json:"__typename"`
			*__premarshalOmitImplsAbstractFragmentInConcreteRandomItemArticle
		}{typename, premarshaled}
		return json.Marshal(result)
	case *OmitImplsAbstractFragmentInConcreteRandomItemTopic:
		typename = "Topic"

		result := struct {
			TypeName string `json:"__typename"`
			*OmitImplsAbstractFragmentInConcreteRandomItemTopic
		}{typename, v}
		return json.Marshal(result)
	case *OmitImplsAbstractFragmentInConcreteRandomItemVideo:
		typename = "Video"

		result := struct {
			TypeName string `json:"__typename"`
			*OmitImplsAbstractFragmentInConcreteRandomItemVideo
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for OmitImplsAbstractFragmentInConcreteRandomItemContent: "%T"`, v)
	}
}

// OmitImplsAbstractFragmentInConcreteRandomItemTopic includes the requested fields of the GraphQL type Topic.
type OmitImplsAbstractFragmentInConcreteRandomItemTopic struct {
	Typename string `json:"__typename"`
	// ID is the identifier of the content.
	Id testutil.ID `json:"id"`
}

// GetTypename returns OmitImplsAbstractFragmentInConcreteRandomItemTopic.Typename, and is useful for accessing the field via an interface.
func (v *OmitImplsAbstractFragmentInConcreteRandomItemTopic) GetTypename() string { return v.Typename }

// GetId returns OmitImplsAbstractFragmentInConcreteRandomItemTopic.Id, and is useful for accessing the field via an interface.
func (v *OmitImplsAbstractFragmentInConcreteRandomItemTopic) GetId() testutil.ID { return v.Id }

// OmitImplsAbstractFragmentInConcreteRandomItemVideo includes the requested fields of the GraphQL type Video.
type OmitImplsAbstractFragmentInConcreteRandomItemVideo struct {
	Typename string `json:"__typename"`
	// ID is the identifier of the content.
	Id testutil.ID `json:"id"`
}

// GetTypename returns OmitImplsAbstractFragmentInConcreteRandomItemVideo.Typename, and is useful for accessing the field via an interface.
func (v *OmitImplsAbstractFragmentInConcreteRandomItemVideo) GetTypename() string { return v.Typename }

// GetId returns OmitImplsAbstractFragmentInConcreteRandomItemVideo.Id, and is useful for accessing the field via an interface.
func (v *OmitImplsAbstractFragmentInConcreteRandomItemVideo) GetId() testutil.ID { return v.Id }

// OmitImplsAbstractFragmentInConcreteResponse is returned by OmitImplsAbstractFragmentInConcrete on success.
type OmitImplsAbstractFragmentInConcreteResponse struct {
	RandomItem OmitImplsAbstractFragmentInConcreteRandomItemContent `json:"-"`
}

// GetRandomItem returns OmitImplsAbstractFragmentInConcreteResponse.RandomItem, and is useful for accessing the field via an interface.
func (v *OmitImplsAbstractFragmentInConcreteResponse) GetRandomItem() OmitImplsAbstractFragmentInConcreteRandomItemContent {
	return v.RandomItem
}

func (v *OmitImplsAbstractFragmentInConcreteResponse) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*OmitImplsAbstractFragmentInConcreteResponse
		RandomItem json.RawMessage `json:"randomItem"`
		graphql.NoUnmarshalJSON
	}
	firstPass.OmitImplsAbstractFragmentInConcreteResponse = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.RandomItem
		src := firstPass.RandomItem
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalOmitImplsAbstractFragmentInConcreteRandomItemContent(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal OmitImplsAbstractFragmentInConcreteResponse.RandomItem: %w", err)
			}
		}
	}
	return nil
}

type __premarshalOmitImplsAbstractFragmentInConcreteResponse struct {
	RandomItem json.RawMessage `json:"randomItem"`
}

func (v *OmitImplsAbstractFragmentInConcreteResponse) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *OmitImplsAbstractFragmentInConcreteResponse) __premarshalJSON() (*__premarshalOmitImplsAbstractFragmentInConcreteResponse, error) {
	var retval __premarshalOmitImplsAbstractFragmentInConcreteResponse

	{

		dst := &retval.RandomItem
		src := v.RandomItem
		var err error
		*dst, err = __marshalOmitImplsAbstractFragmentInConcreteRandomItemContent(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal OmitImplsAbstractFragmentInConcreteResponse.RandomItem: %w", err)
		}
	}
	return &retval, nil
}

// The query executed by OmitImplsAbstractFragmentInConcrete.
const OmitImplsAbstractFragmentInConcrete_Operation = `
query OmitImplsAbstractFragmentInConcrete {
	randomItem {
		__typename
		id
		... on Article {
			text
			... ContentBasics
		}
	}
}
fragment ContentBasics on Content {
	id
	name
}
`

func OmitImplsAbstractFragmentInConcrete(
	client_ graphql.Client,
) (data_ *OmitImplsAbstractFragmentInConcreteResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "OmitImplsAbstractFragmentInConcrete",
		Query:  OmitImplsAbstractFragmentInConcrete_Operation,
	}

	data_ = &OmitImplsAbstractFragmentInConcreteResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		nil,
		req_,
		resp_,
	)

	return data_, err_
}

