// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package queries

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/Khan/genqlient/graphql"
)

// NamedContentFields includes the GraphQL fields of Content requested by the fragment NamedContentFields.
// The GraphQL type's documentation follows.
//
// Content is implemented by various types like Article, Video, and Topic.
//
// NamedContentFields is implemented by the following types:
// NamedContentFieldsArticle
// NamedContentFieldsGenqlientOther
type NamedContentFields interface {
	implementsGraphQLInterfaceNamedContentFields()
	// GetId returns the interface-field "id" from its implementation.
	// The GraphQL interface field's documentation follows.
	//
	// ID is the identifier of the content.
	GetId() string
	// GetName returns the interface-field "name" from its implementation.
	GetName() string
}

func (v *NamedContentFieldsArticle) implementsGraphQLInterfaceNamedContentFields()        {}
func (v *NamedContentFieldsGenqlientOther) implementsGraphQLInterfaceNamedContentFields() {}

func __unmarshalNamedContentFields(b []byte, v *NamedContentFields) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "Article":
		*v = new(NamedContentFieldsArticle)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing Content.__typename")
	default:
		*v = new(NamedContentFieldsGenqlientOther)
		return json.Unmarshal(b, *v)
	}
}

func __marshalNamedContentFields(v *NamedContentFields) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *NamedContentFieldsArticle:
		typename = "Article"

		result := struct {
			TypeName string `json:"__typename"`
			*NamedContentFieldsArticle
		}{typename, v}
		return json.Marshal(result)
	case *NamedContentFieldsGenqlientOther:
		return json.Marshal(v)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for NamedContentFields: "%T"`, v)
	}
}

// NamedContentFields includes the GraphQL fields of Article requested by the fragment NamedContentFields.
// The GraphQL type's documentation follows.
//
// Content is implemented by various types like Article, Video, and Topic.
type NamedContentFieldsArticle struct {
	// ID is the identifier of the content.
	Id   string `json:"id"`
	Name string `json:"name"`
	Text string `json:"text"`
}

// GetId returns NamedContentFieldsArticle.Id, and is useful for accessing the field via an interface.
func (v *NamedContentFieldsArticle) GetId() string { return v.Id }

// GetName returns NamedContentFieldsArticle.Name, and is useful for accessing the field via an interface.
func (v *NamedContentFieldsArticle) GetName() string { return v.Name }

// GetText returns NamedContentFieldsArticle.Text, and is useful for accessing the field via an interface.
func (v *NamedContentFieldsArticle) GetText() string { return v.Text }

// NamedContentFieldsGenqlientOther is the catch-all for NamedContentFields implementations that aren't explicitly fragmented; the concrete type-name is in __typename.
type NamedContentFieldsGenqlientOther struct {
	// ID is the identifier of the content.
	Id   string `json:"id"`
	Name string `json:"name"`
}

// GetId returns NamedContentFieldsGenqlientOther.Id, and is useful for accessing the field via an interface.
func (v *NamedContentFieldsGenqlientOther) GetId() string { return v.Id }

// GetName returns NamedContentFieldsGenqlientOther.Name, and is useful for accessing the field via an interface.
func (v *NamedContentFieldsGenqlientOther) GetName() string { return v.Name }

// OmitImplsNamedFragmentOnInterfaceRandomItemArticle includes the requested fields of the GraphQL type Article.
type OmitImplsNamedFragmentOnInterfaceRandomItemArticle struct {
	Typename                  string `json:"__typename"`
	NamedContentFieldsArticle `json:"-"`
}

// GetTypename returns OmitImplsNamedFragmentOnInterfaceRandomItemArticle.Typename, and is useful for accessing the field via an interface.
func (v *OmitImplsNamedFragmentOnInterfaceRandomItemArticle) GetTypename() string { return v.Typename }

// GetId returns OmitImplsNamedFragmentOnInterfaceRandomItemArticle.Id, and is useful for accessing the field via an interface.
func (v *OmitImplsNamedFragmentOnInterfaceRandomItemArticle) GetId() string {
	return v.NamedContentFieldsArticle.Id
}

// GetName returns OmitImplsNamedFragmentOnInterfaceRandomItemArticle.Name, and is useful for accessing the field via an interface.
func (v *OmitImplsNamedFragmentOnInterfaceRandomItemArticle) GetName() string {
	return v.NamedContentFieldsArticle.Name
}

// GetText returns OmitImplsNamedFragmentOnInterfaceRandomItemArticle.Text, and is useful for accessing the field via an interface.
func (v *OmitImplsNamedFragmentOnInterfaceRandomItemArticle) GetText() string {
	return v.NamedContentFieldsArticle.Text
}

func (v *OmitImplsNamedFragmentOnInterfaceRandomItemArticle) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*OmitImplsNamedFragmentOnInterfaceRandomItemArticle
		graphql.NoUnmarshalJSON
	}
	firstPass.OmitImplsNamedFragmentOnInterfaceRandomItemArticle = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.NamedContentFieldsArticle)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalOmitImplsNamedFragmentOnInterfaceRandomItemArticle struct {
	Typename string `json:"__typename"`

	Id string `json:"id"`

	Name string `json:"name"`

	Text string `json:"text"`
}

func (v *OmitImplsNamedFragmentOnInterfaceRandomItemArticle) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *OmitImplsNamedFragmentOnInterfaceRandomItemArticle) __premarshalJSON() (*__premarshalOmitImplsNamedFragmentOnInterfaceRandomItemArticle, error) {
	var retval __premarshalOmitImplsNamedFragmentOnInterfaceRandomItemArticle

	retval.Typename = v.Typename
	retval.Id = v.NamedContentFieldsArticle.Id
	retval.Name = v.NamedContentFieldsArticle.Name
	retval.Text = v.NamedContentFieldsArticle.Text
	return &retval, nil
}

// OmitImplsNamedFragmentOnInterfaceRandomItemContent includes the requested fields of the GraphQL interface Content.
//
// OmitImplsNamedFragmentOnInterfaceRandomItemContent is implemented by the following types:
// OmitImplsNamedFragmentOnInterfaceRandomItemArticle
// OmitImplsNamedFragmentOnInterfaceRandomItemContentGenqlientOther
// The GraphQL type's documentation follows.
//
// Content is implemented by various types like Article, Video, and Topic.
type OmitImplsNamedFragmentOnInterfaceRandomItemContent interface {
	implementsGraphQLInterfaceOmitImplsNamedFragmentOnInterfaceRandomItemContent()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
	NamedContentFields
}

func (v *OmitImplsNamedFragmentOnInterfaceRandomItemArticle) implementsGraphQLInterfaceOmitImplsNamedFragmentOnInterfaceRandomItemContent() {
}
func (v *OmitImplsNamedFragmentOnInterfaceRandomItemContentGenqlientOther) implementsGraphQLInterfaceOmitImplsNamedFragmentOnInterfaceRandomItemContent() {
}

func __unmarshalOmitImplsNamedFragmentOnInterfaceRandomItemContent(b []byte, v *OmitImplsNamedFragmentOnInterfaceRandomItemContent) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "Article":
		*v = new(OmitImplsNamedFragmentOnInterfaceRandomItemArticle)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing Content.__typename")
	default:
		*v = new(OmitImplsNamedFragmentOnInterfaceRandomItemContentGenqlientOther)
		return json.Unmarshal(b, *v)
	}
}

func __marshalOmitImplsNamedFragmentOnInterfaceRandomItemContent(v *OmitImplsNamedFragmentOnInterfaceRandomItemContent) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *OmitImplsNamedFragmentOnInterfaceRandomItemArticle:
		typename = "Article"

		premarshaled, err := v.__premarshalJSON()
		if err != nil {
			return nil, err
		}
		result := struct {
			TypeName string `json:"__typename"`
			*__premarshalOmitImplsNamedFragmentOnInterfaceRandomItemArticle
		}{typename, premarshaled}
		return json.Marshal(result)
	case *OmitImplsNamedFragmentOnInterfaceRandomItemContentGenqlientOther:
		premarshaled, err := v.__premarshalJSON()
		if err != nil {
			return nil, err
		}
		return json.Marshal(premarshaled)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for OmitImplsNamedFragmentOnInterfaceRandomItemContent: "%T"`, v)
	}
}

// OmitImplsNamedFragmentOnInterfaceRandomItemContentGenqlientOther is the catch-all for OmitImplsNamedFragmentOnInterfaceRandomItemContent implementations that aren't explicitly fragmented; the concrete type-name is in __typename.
type OmitImplsNamedFragmentOnInterfaceRandomItemContentGenqlientOther struct {
	Typename                         string `json:"__typename"`
	NamedContentFieldsGenqlientOther `json:"-"`
}

// GetTypename returns OmitImplsNamedFragmentOnInterfaceRandomItemContentGenqlientOther.Typename, and is useful for accessing the field via an interface.
func (v *OmitImplsNamedFragmentOnInterfaceRandomItemContentGenqlientOther) GetTypename() string {
	return v.Typename
}

// GetId returns OmitImplsNamedFragmentOnInterfaceRandomItemContentGenqlientOther.Id, and is useful for accessing the field via an interface.
func (v *OmitImplsNamedFragmentOnInterfaceRandomItemContentGenqlientOther) GetId() string {
	return v.NamedContentFieldsGenqlientOther.Id
}

// GetName returns OmitImplsNamedFragmentOnInterfaceRandomItemContentGenqlientOther.Name, and is useful for accessing the field via an interface.
func (v *OmitImplsNamedFragmentOnInterfaceRandomItemContentGenqlientOther) GetName() string {
	return v.NamedContentFieldsGenqlientOther.Name
}

func (v *OmitImplsNamedFragmentOnInterfaceRandomItemContentGenqlientOther) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*OmitImplsNamedFragmentOnInterfaceRandomItemContentGenqlientOther
		graphql.NoUnmarshalJSON
	}
	firstPass.OmitImplsNamedFragmentOnInterfaceRandomItemContentGenqlientOther = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.NamedContentFieldsGenqlientOther)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalOmitImplsNamedFragmentOnInterfaceRandomItemContentGenqlientOther struct {
	Typename string `json:"__typename"`

	Id string `json:"id"`

	Name string `json:"name"`
}

func (v *OmitImplsNamedFragmentOnInterfaceRandomItemContentGenqlientOther) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *OmitImplsNamedFragmentOnInterfaceRandomItemContentGenqlientOther) __premarshalJSON() (*__premarshalOmitImplsNamedFragmentOnInterfaceRandomItemContentGenqlientOther, error) {
	var retval __premarshalOmitImplsNamedFragmentOnInterfaceRandomItemContentGenqlientOther

	retval.Typename = v.Typename
	retval.Id = v.NamedContentFieldsGenqlientOther.Id
	retval.Name = v.NamedContentFieldsGenqlientOther.Name
	return &retval, nil
}

// OmitImplsNamedFragmentOnInterfaceResponse is returned by OmitImplsNamedFragmentOnInterface on success.
type OmitImplsNamedFragmentOnInterfaceResponse struct {
	RandomItem OmitImplsNamedFragmentOnInterfaceRandomItemContent `json:"-"`
}

// GetRandomItem returns OmitImplsNamedFragmentOnInterfaceResponse.RandomItem, and is useful for accessing the field via an interface.
func (v *OmitImplsNamedFragmentOnInterfaceResponse) GetRandomItem() OmitImplsNamedFragmentOnInterfaceRandomItemContent {
	return v.RandomItem
}

func (v *OmitImplsNamedFragmentOnInterfaceResponse) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*OmitImplsNamedFragmentOnInterfaceResponse
		RandomItem json.RawMessage `json:"randomItem"`
		graphql.NoUnmarshalJSON
	}
	firstPass.OmitImplsNamedFragmentOnInterfaceResponse = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.RandomItem
		src := firstPass.RandomItem
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalOmitImplsNamedFragmentOnInterfaceRandomItemContent(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal OmitImplsNamedFragmentOnInterfaceResponse.RandomItem: %w", err)
			}
		}
	}
	return nil
}

type __premarshalOmitImplsNamedFragmentOnInterfaceResponse struct {
	RandomItem json.RawMessage `json:"randomItem"`
}

func (v *OmitImplsNamedFragmentOnInterfaceResponse) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *OmitImplsNamedFragmentOnInterfaceResponse) __premarshalJSON() (*__premarshalOmitImplsNamedFragmentOnInterfaceResponse, error) {
	var retval __premarshalOmitImplsNamedFragmentOnInterfaceResponse

	{

		dst := &retval.RandomItem
		src := v.RandomItem
		var err error
		*dst, err = __marshalOmitImplsNamedFragmentOnInterfaceRandomItemContent(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal OmitImplsNamedFragmentOnInterfaceResponse.RandomItem: %w", err)
		}
	}
	return &retval, nil
}

// The query executed by OmitImplsNamedFragmentOnInterface.
const OmitImplsNamedFragmentOnInterface_Operation = `
query OmitImplsNamedFragmentOnInterface {
	randomItem {
		__typename
		... NamedContentFields
	}
}
fragment NamedContentFields on Content {
	id
	name
	... on Article {
		text
	}
}
`

func OmitImplsNamedFragmentOnInterface(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *OmitImplsNamedFragmentOnInterfaceResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "OmitImplsNamedFragmentOnInterface",
		Query:  OmitImplsNamedFragmentOnInterface_Operation,
	}

	data_ = &OmitImplsNamedFragmentOnInterfaceResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

